
# GitHub Action for deploying to Firebase Hosting on merge to main branch
# This workflow builds and deploys your Next.js app to the live channel.

name: Deploy to Firebase Hosting (Live)

on:
  push:
    branches:
      - main # Or your project's default branch (e.g., master)

jobs:
  build_and_deploy_live:
    runs-on: ubuntu-latest
    # Environment variables for the build process if needed (e.g., for Genkit during build)
    # env:
      # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY_BUILD }} # If Genkit is used during 'npm run build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        # If your build needs GOOGLE_API_KEY:
        # env:
        #   GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY_BUILD }}

      - name: Deploy to Firebase Hosting (Live Channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' # GitHub Secret containing your Firebase service account JSON
          projectId: '${{ vars.FIREBASE_PROJECT_ID }}' # GitHub Variable for your Firebase Project ID
          channelId: live # Deploy to the live channel
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # Required for App Hosting
